Rails.application.routes.draw do
  # resources :dogs
  # resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get '/dogs', to: 'dogs#index', as: 'dogs'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
get '/dog/new', to: 'dogs#new', as: 'new_dog'
get '/dogs/:id', to: 'dogs#show', as: 'dog'
get '/employees', to: 'employees#index', as: 'employees'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
get '/employees/new', to: 'employees#new', as: 'new_employee'
post '/employees', to: "employees#create"
get '/employees/:id', to: 'employees#show', as: 'employee'
get 'employees/:id/edit', to: 'employees#edit', as: 'edit_employee'
patch 'employees/:id', to: 'employees#update'
end
